### PR TITLE
add translator file

### PR DESCRIPTION
**Pull request by change2hao**
add translator file for nshipster.cn

### CODE REVIEW

**Comment by rickytan** [comment]
看了博主的 blog，首页列出了所有内容，有点长，可以在文章中合适的地方添加   断掉，自动生成一个阅读全文的链接

**Comment by change2hao** [comment]
@rickytan 谢谢你到建议，我已经修正 ：）

**Comment by croath** [comment]
Thanks for your contributions.

:beers: Welcome @change2hao !

**Comment by croath** [comment]
@rickytan I just checked out @change2hao 's blog about translation tips. It maybe helps a lot to new partners joining the translation group. So why not opening an issue to discuss and summarise some common tips?

**Pull request merged**
