### PR TITLE
Update to Jekyll 4

### PR DESCRIPTION
**Pull request by mattt**

### CODE REVIEW

**Comment by mattt** [comment]
@NSHipster/translators I'm evaluating an upgrade to Jekyll 4 for building all of the NSHipster websites. Please take a look at the respective preview for each translation and let me know if you notice any rendering issues. Thanks!

- [NSHipster.cn Deploy Preview](https://deploy-preview-44--nshipster-cn.netlify.com/)
- [NSHipster.es Deploy Preview](https://deploy-preview-44--nshipster-es.netlify.com)
- [NSHipster.co.kr Deploy Preview](https://deploy-preview-44--nshipster-co-kr.netlify.com/)

**Comment by jfsagasti** [comment]
Hi Mattt, looks great! The only exceptions I've found:

* "Miscellaneous" wasn't translated to "Miscelánea" in home.  
* Your author excerpt in articles is still in English.

**Comment by mattt** [comment]
@croath Thanks for reviewing! I'm excited that Jekyll 4 improves build performance by ~50% from a cold start.

**Comment by mattt** [comment]
@pilgwon The current CSS apply serif-style fonts to section headers that aren't in an article (so "최근 기사", "책", and the untranslated "Cocoa", "Swift", and "Miscellaneous"). Please open an issue if you think those should use the same article body font from before, and I'll take a look. Thanks!

**Comment by mattt** [comment]
@jfsagasti Thanks for pointing those out! I just opened Issue #45 to track the work necessary to localize category names like "Miscellaneous".

**Pull request merged**
