### PR TITLE
add jiathis for sharing to SNS

### PR DESCRIPTION
**Pull request by rickytan**

### CODE REVIEW

**Comment by rickytan** [comment]
@croath 意下如何？

**Comment by croath** [comment]
LGTM but I think you'd better append a screenshot here.

I know what does the plugin look like but it's *a little bit not-that-beautiful*. Shall we customise small icons which will fit NSHipster's UI style better according to http://jiathis.com/help/html/customize-the-icons ?


BTW @natecook1000 please check this out! It's a social sharing module including most of SNS websites inside of China. We wanna provide a convenient way for sharing.

**Comment by natecook1000** [comment]
@rickytan Sorry to be MIA on this for so long! Can you attach a screenshot of what this looks like on your system? For me it doesn't ever come fully on screen…

**Comment by rickytan** [comment]
Same with me , and I don't know why. Maybe there's a style conflict ?

**Pull request merged**
